<AutoPilot:project xmlns:AutoPilot="com.autoesl.autopilot.project" projectType="C/C++" name="design_1_v_mix_0_0" top="v_mix">
    <solutions>
        <solution name="prj" status=""/>
    </solutions>
    <files>
        <file name="c:/FPGAProjects/CS1/CS1.gen/sources_1/bd/design_1/ip/design_1_v_mix_0_0/src/hls/hls_video_undistort.h" sc="0" tb="false" cflags="-Ic:/FPGAProjects/CS1/CS1.gen/sources_1/bd/design_1/ip/design_1_v_mix_0_0/src/hls -Ic:/FPGAProjects/CS1/CS1.gen/sources_1/bd/design_1/ip/design_1_v_mix_0_0/src" csimflags="" blackbox="false"/>
        <file name="c:/FPGAProjects/CS1/CS1.gen/sources_1/bd/design_1/ip/design_1_v_mix_0_0/src/hls/hls_video_types.h" sc="0" tb="false" cflags="-Ic:/FPGAProjects/CS1/CS1.gen/sources_1/bd/design_1/ip/design_1_v_mix_0_0/src/hls -Ic:/FPGAProjects/CS1/CS1.gen/sources_1/bd/design_1/ip/design_1_v_mix_0_0/src" csimflags="" blackbox="false"/>
        <file name="c:/FPGAProjects/CS1/CS1.gen/sources_1/bd/design_1/ip/design_1_v_mix_0_0/src/hls/hls_video_stereobm.h" sc="0" tb="false" cflags="-Ic:/FPGAProjects/CS1/CS1.gen/sources_1/bd/design_1/ip/design_1_v_mix_0_0/src/hls -Ic:/FPGAProjects/CS1/CS1.gen/sources_1/bd/design_1/ip/design_1_v_mix_0_0/src" csimflags="" blackbox="false"/>
        <file name="c:/FPGAProjects/CS1/CS1.gen/sources_1/bd/design_1/ip/design_1_v_mix_0_0/src/hls/hls_video_mem.h" sc="0" tb="false" cflags="-Ic:/FPGAProjects/CS1/CS1.gen/sources_1/bd/design_1/ip/design_1_v_mix_0_0/src/hls -Ic:/FPGAProjects/CS1/CS1.gen/sources_1/bd/design_1/ip/design_1_v_mix_0_0/src" csimflags="" blackbox="false"/>
        <file name="c:/FPGAProjects/CS1/CS1.gen/sources_1/bd/design_1/ip/design_1_v_mix_0_0/src/hls/hls_video_io.h" sc="0" tb="false" cflags="-Ic:/FPGAProjects/CS1/CS1.gen/sources_1/bd/design_1/ip/design_1_v_mix_0_0/src/hls -Ic:/FPGAProjects/CS1/CS1.gen/sources_1/bd/design_1/ip/design_1_v_mix_0_0/src" csimflags="" blackbox="false"/>
        <file name="c:/FPGAProjects/CS1/CS1.gen/sources_1/bd/design_1/ip/design_1_v_mix_0_0/src/hls/hls_video_imgproc.h" sc="0" tb="false" cflags="-Ic:/FPGAProjects/CS1/CS1.gen/sources_1/bd/design_1/ip/design_1_v_mix_0_0/src/hls -Ic:/FPGAProjects/CS1/CS1.gen/sources_1/bd/design_1/ip/design_1_v_mix_0_0/src" csimflags="" blackbox="false"/>
        <file name="c:/FPGAProjects/CS1/CS1.gen/sources_1/bd/design_1/ip/design_1_v_mix_0_0/src/hls/hls_video_imgbase.h" sc="0" tb="false" cflags="-Ic:/FPGAProjects/CS1/CS1.gen/sources_1/bd/design_1/ip/design_1_v_mix_0_0/src/hls -Ic:/FPGAProjects/CS1/CS1.gen/sources_1/bd/design_1/ip/design_1_v_mix_0_0/src" csimflags="" blackbox="false"/>
        <file name="c:/FPGAProjects/CS1/CS1.gen/sources_1/bd/design_1/ip/design_1_v_mix_0_0/src/hls/hls_video_hough.h" sc="0" tb="false" cflags="-Ic:/FPGAProjects/CS1/CS1.gen/sources_1/bd/design_1/ip/design_1_v_mix_0_0/src/hls -Ic:/FPGAProjects/CS1/CS1.gen/sources_1/bd/design_1/ip/design_1_v_mix_0_0/src" csimflags="" blackbox="false"/>
        <file name="c:/FPGAProjects/CS1/CS1.gen/sources_1/bd/design_1/ip/design_1_v_mix_0_0/src/hls/hls_video_histogram.h" sc="0" tb="false" cflags="-Ic:/FPGAProjects/CS1/CS1.gen/sources_1/bd/design_1/ip/design_1_v_mix_0_0/src/hls -Ic:/FPGAProjects/CS1/CS1.gen/sources_1/bd/design_1/ip/design_1_v_mix_0_0/src" csimflags="" blackbox="false"/>
        <file name="c:/FPGAProjects/CS1/CS1.gen/sources_1/bd/design_1/ip/design_1_v_mix_0_0/src/hls/hls_video_harris.h" sc="0" tb="false" cflags="-Ic:/FPGAProjects/CS1/CS1.gen/sources_1/bd/design_1/ip/design_1_v_mix_0_0/src/hls -Ic:/FPGAProjects/CS1/CS1.gen/sources_1/bd/design_1/ip/design_1_v_mix_0_0/src" csimflags="" blackbox="false"/>
        <file name="c:/FPGAProjects/CS1/CS1.gen/sources_1/bd/design_1/ip/design_1_v_mix_0_0/src/hls/hls_video_haar.h" sc="0" tb="false" cflags="-Ic:/FPGAProjects/CS1/CS1.gen/sources_1/bd/design_1/ip/design_1_v_mix_0_0/src/hls -Ic:/FPGAProjects/CS1/CS1.gen/sources_1/bd/design_1/ip/design_1_v_mix_0_0/src" csimflags="" blackbox="false"/>
        <file name="c:/FPGAProjects/CS1/CS1.gen/sources_1/bd/design_1/ip/design_1_v_mix_0_0/src/hls/hls_video_fast.h" sc="0" tb="false" cflags="-Ic:/FPGAProjects/CS1/CS1.gen/sources_1/bd/design_1/ip/design_1_v_mix_0_0/src/hls -Ic:/FPGAProjects/CS1/CS1.gen/sources_1/bd/design_1/ip/design_1_v_mix_0_0/src" csimflags="" blackbox="false"/>
        <file name="c:/FPGAProjects/CS1/CS1.gen/sources_1/bd/design_1/ip/design_1_v_mix_0_0/src/hls/hls_video_core.h" sc="0" tb="false" cflags="-Ic:/FPGAProjects/CS1/CS1.gen/sources_1/bd/design_1/ip/design_1_v_mix_0_0/src/hls -Ic:/FPGAProjects/CS1/CS1.gen/sources_1/bd/design_1/ip/design_1_v_mix_0_0/src" csimflags="" blackbox="false"/>
        <file name="c:/FPGAProjects/CS1/CS1.gen/sources_1/bd/design_1/ip/design_1_v_mix_0_0/src/hls/hls_video_arithm.h" sc="0" tb="false" cflags="-Ic:/FPGAProjects/CS1/CS1.gen/sources_1/bd/design_1/ip/design_1_v_mix_0_0/src/hls -Ic:/FPGAProjects/CS1/CS1.gen/sources_1/bd/design_1/ip/design_1_v_mix_0_0/src" csimflags="" blackbox="false"/>
        <file name="c:/FPGAProjects/CS1/CS1.gen/sources_1/bd/design_1/ip/design_1_v_mix_0_0/src/hls/hls_axi_io.h" sc="0" tb="false" cflags="-Ic:/FPGAProjects/CS1/CS1.gen/sources_1/bd/design_1/ip/design_1_v_mix_0_0/src/hls -Ic:/FPGAProjects/CS1/CS1.gen/sources_1/bd/design_1/ip/design_1_v_mix_0_0/src" csimflags="" blackbox="false"/>
        <file name="c:/FPGAProjects/CS1/CS1.gen/sources_1/bd/design_1/ip/design_1_v_mix_0_0/src/hls_opencv.h" sc="0" tb="false" cflags="-Ic:/FPGAProjects/CS1/CS1.gen/sources_1/bd/design_1/ip/design_1_v_mix_0_0/src/hls -Ic:/FPGAProjects/CS1/CS1.gen/sources_1/bd/design_1/ip/design_1_v_mix_0_0/src" csimflags="" blackbox="false"/>
        <file name="c:/FPGAProjects/CS1/CS1.gen/sources_1/bd/design_1/ip/design_1_v_mix_0_0/src/hls_video.h" sc="0" tb="false" cflags="-Ic:/FPGAProjects/CS1/CS1.gen/sources_1/bd/design_1/ip/design_1_v_mix_0_0/src/hls -Ic:/FPGAProjects/CS1/CS1.gen/sources_1/bd/design_1/ip/design_1_v_mix_0_0/src" csimflags="" blackbox="false"/>
        <file name="c:/FPGAProjects/CS1/CS1.gen/sources_1/bd/design_1/ip/design_1_v_mix_0_0/src/v_csc.h" sc="0" tb="false" cflags="-Ic:/FPGAProjects/CS1/CS1.gen/sources_1/bd/design_1/ip/design_1_v_mix_0_0/src/hls -Ic:/FPGAProjects/CS1/CS1.gen/sources_1/bd/design_1/ip/design_1_v_mix_0_0/src" csimflags="" blackbox="false"/>
        <file name="c:/FPGAProjects/CS1/CS1.gen/sources_1/bd/design_1/ip/design_1_v_mix_0_0/src/v_csc.cpp" sc="0" tb="false" cflags="-Ic:/FPGAProjects/CS1/CS1.gen/sources_1/bd/design_1/ip/design_1_v_mix_0_0/src/hls -Ic:/FPGAProjects/CS1/CS1.gen/sources_1/bd/design_1/ip/design_1_v_mix_0_0/src" csimflags="" blackbox="false"/>
        <file name="c:/FPGAProjects/CS1/CS1.gen/sources_1/bd/design_1/ip/design_1_v_mix_0_0/src/v_dma.h" sc="0" tb="false" cflags="-Ic:/FPGAProjects/CS1/CS1.gen/sources_1/bd/design_1/ip/design_1_v_mix_0_0/src/hls -Ic:/FPGAProjects/CS1/CS1.gen/sources_1/bd/design_1/ip/design_1_v_mix_0_0/src" csimflags="" blackbox="false"/>
        <file name="c:/FPGAProjects/CS1/CS1.gen/sources_1/bd/design_1/ip/design_1_v_mix_0_0/src/v_dma.cpp" sc="0" tb="false" cflags="-Ic:/FPGAProjects/CS1/CS1.gen/sources_1/bd/design_1/ip/design_1_v_mix_0_0/src/hls -Ic:/FPGAProjects/CS1/CS1.gen/sources_1/bd/design_1/ip/design_1_v_mix_0_0/src" csimflags="" blackbox="false"/>
        <file name="c:/FPGAProjects/CS1/CS1.gen/sources_1/bd/design_1/ip/design_1_v_mix_0_0/src/v_mix.h" sc="0" tb="false" cflags="-Ic:/FPGAProjects/CS1/CS1.gen/sources_1/bd/design_1/ip/design_1_v_mix_0_0/src/hls -Ic:/FPGAProjects/CS1/CS1.gen/sources_1/bd/design_1/ip/design_1_v_mix_0_0/src" csimflags="" blackbox="false"/>
        <file name="c:/FPGAProjects/CS1/CS1.gen/sources_1/bd/design_1/ip/design_1_v_mix_0_0/src/v_mix.cpp" sc="0" tb="false" cflags="-Ic:/FPGAProjects/CS1/CS1.gen/sources_1/bd/design_1/ip/design_1_v_mix_0_0/src/hls -Ic:/FPGAProjects/CS1/CS1.gen/sources_1/bd/design_1/ip/design_1_v_mix_0_0/src" csimflags="" blackbox="false"/>
        <file name="c:/FPGAProjects/CS1/CS1.gen/sources_1/bd/design_1/ip/design_1_v_mix_0_0/src/v_mix_config.h" sc="0" tb="false" cflags="-Ic:/FPGAProjects/CS1/CS1.gen/sources_1/bd/design_1/ip/design_1_v_mix_0_0/src/hls -Ic:/FPGAProjects/CS1/CS1.gen/sources_1/bd/design_1/ip/design_1_v_mix_0_0/src" csimflags="" blackbox="false"/>
    </files>
</AutoPilot:project>

